services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend