vpc_name           = "clickops-dev-vpc"
cidr_block         = "10.0.0.0/16"
subnet_name        = "clickops-dev-public-subnet"
public_subnet_cidr = "10.0.1.0/24"

sg_name        = "clickops-dev-sg"
ec2_name       = "clickops-dev-ec2"
iam_role_name  = "clickops-dev-ec2-role"
s3_bucket      = "clickops-dev-bucket-vikram-2026-003"
ecr_repo       = "clickops-dev-ecr"
secret_name    = "clickops-sm-dev-2"
instance_type  = "t3.micro"
key_name       = "gv"