name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: Set Environment
      run: |
        if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
          echo "ENV=dev" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF##*/}" == "qa" ]]; then
          echo "ENV=qa" >> $GITHUB_ENV
        else
          echo "ENV=prd" >> $GITHUB_ENV
        fi

    - name: Terraform Init
      run: |
        cd terraform/environment/${ENV}
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform/environment/${ENV}
        terraform plan -var-file=${ENV}.tfvars

    - name: Terraform Apply
      run: |
        cd terraform/environment/${ENV}
        terraform apply -auto-approve -var-file=${ENV}.tfvars